spring:
  application:
    name: tranquil-nest

  datasource:
    url: jdbc:mysql://localhost:3306/tranquil_nest
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signer-key: "yU7YKOsktvkVKyz5kC1G/OFpBBZe+tuYPZJEYtUum4G2JrJXadVMJn08cVdduQTZ"
  valid-duration: 36000 # in seconds